### ISSUE TITLE
Facebook events and posts not updating

### ISSUE THREAD

**Issue by brettdonald** [adventistmedia/simple_church#13]
Events and posts from our [Facebook page](https://www.facebook.com/castlehilladventistchurch) are not updating on our Simple Church web site. The most recent post showing in Simple Church is from 5th Dec 2016, but we have posted at least 6 times since then. There are no events showing in Simple Church, but our page has at least 2 events.

![simplechurch1](https://cloud.githubusercontent.com/assets/4504348/23145747/c88f9ac6-f824-11e6-8daf-e11c6a289137.png)
![simplechurch2](https://cloud.githubusercontent.com/assets/4504348/23145748/ca7ef69c-f824-11e6-9cac-d6be3cce804a.png)

**Comment by Scotttie** [comment]
Castle Hill has both a FB Page, and a Public Group both with Status ACTIVE. (we can probably remove the Group actually, but will leave it there for bug hunting for now)
The photos are rather empty also.

https://www.facebook.com/castlehilladventistchurch
https://www.facebook.com/groups/castlehilladventist
https://castlehill.adventistchurch.com
https://places.adventistchurch.com/dashboard/places/15/facebook_pages

**Comment by Scotttie** [comment]
We've tried turning it off and on again....
Can you approve again, Brett?

**Comment by brettdonald** [comment]
Done. So now I can see the new Event I added this morning, that's great. Can see more photos, so that's good too. But the news section seems to have disappeared, that's not so good. Also, Scott, Dan informs me that this morning you made **castlehill.adventist.org.au** our default domain name rather than **castlehill.adventistchurch.com** -- that change was in effect for a while, but now seems to have reverted back.

**Comment by Scotttie** [comment]
we were testing something re domain, back to ad.org.au now - sorry.
Must nut out the news some more....

**Comment by brettdonald** [comment]
I didn't notice this yesterday, but the event is now showing the wrong image. Should be an image of a Korean choir all dressed in pink.

![simplechurch3](https://cloud.githubusercontent.com/assets/4504348/23189582/adbd1d40-f8e7-11e6-94d5-58a3a60cb6d4.png)

**Comment by Scotttie** [comment]
All event images  are currently overwritten, but I have another ticket to look at allowing responsible event posters to use their own good images. It'as a very clever system but not helpful always, as in this case.

**Comment by Scotttie** [comment]
Confirming: newly added  FB events still not appearing.
https://demo.adventistchurch.com/

**Comment by Scotttie** [comment]
For Castle Hill, no news is appearing on site:
http://castlehill.adventist.org.au is the page
https://www.facebook.com/pg/castlehilladventistchurch/posts/?ref=page_internal shows some posts that should meet the criteria to show up. 
https://places.adventistchurch.com/dashboard/places/15/facebook_pages shows it's active

**Comment by Scotttie** [comment]
News and Events flowing now (and user images showing too), just a matter of tweaking what and how it all appears, as noted in other tickets and internal discussions. So closing up this ticket for now.
